#https://github.com/oss-review-toolkit/ort/blob/main/model/src/main/resources/reference.yml
ort:
  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true
  forceOverwrite: true

  analyzer:
    allowDynamicVersions: true
    # A list of enabled package managers.
    enabledPackageManagers: [NPM]
    skipExcluded: true
    packageManagers:
      NPM: {}

  downloader:
    # We don't want excluded stuff to be downloaded, e.g. dev or test dependencies
    skipExcluded: true

  advisor:
    # A flag to control whether excluded scopes and paths should be skipped when giving the advice.
    skipExcluded: true

  scanner:
    # We don't want excluded stuff to be scanned, e.g. dev or test dependencies
    skipExcluded: true

  reporter:
    config:
      SpdxDocument:
        options:
          # This flag controls, if detailed scan results on file level should be included into the SPDX file. This increases file size.
          file.information.enabled: true
