- id: "NPM::ckeditor4:4.22.0"
  curations:
    comment: >-
      We use ckeditor.js distribution file with title says "CKEditor 4 Open-Source edition (4.22.* and below) is
      licensed under the terms of any of the following licenses at your choice: 1.GNU General Public License Version 2 or later.
      2.GNU Lesser General Public License Version 2.1 or later. 3.Mozilla Public License Version 1.1 or later." We can conclude
      that the license is MPL-1.1.
    concluded_license: "MPL-1.1"
    is_modified: false
    is_metadata_only: false
    homepage_url: "https://ckeditor.com/ckeditor-4/"
    vcs:
      type: "Git"
      url: "https://github.com/ckeditor/ckeditor4.git"
      revision: "d529d176d70016ce8bcf51eb87ce7802a05fe5f9"
